#include "database.h"
#include "./adt/wordmachine.h"
#include "./adt/boolean.h"
#include "./adt/wordmachine.h"
#include "permintaanpertemanan.h"
#include "teman.h"
#include "profil.h"
#include "draf.h"
#include "simpan.h"
void perintah();
//Menjalankan perintah